services:
  atuador:
    build:
      context: .
      dockerfile: ./device/Dockerfile
    command: ./atuador_bin
    ports:
      - "8081:8081"
    environment:
      - ID_ATUADOR=1
      - PORTA_ATUADOR=8081
      - TOTAL_EQUIPAMENTOS=5
    volumes:
      - ./fisica:/app/fisica
    networks:
      - rede_iot

  sensor1:
    build:
      context: .
      dockerfile: ./device/Dockerfile
    command: ./sensor_bin
    environment:
      - ID_SENSOR=1
      - NOME=Geladeira_1
      - TIPO_SENSOR=geladeira
      - TEMP_MIN=2.0
      - TEMP_MAX=4.5
      - HOST_INTEGRADOR=172.16.103.2:9090
    volumes:
      - ./fisica:/app/fisica
    networks:
      - rede_iot
    depends_on: [atuador]

  sensor2:
    build:
      context: .
      dockerfile: ./device/Dockerfile
    command: ./sensor_bin
    environment:
      - ID_SENSOR=2
      - NOME=Geladeira_2
      - TIPO_SENSOR=geladeira
      - TEMP_MIN=1.0
      - TEMP_MAX=3.0
      - HOST_INTEGRADOR=172.16.103.2:9090
    volumes:
      - ./fisica:/app/fisica
    networks:
      - rede_iot
    depends_on: [atuador]

  sensor3:
    build:
      context: .
      dockerfile: ./device/Dockerfile
    command: ./sensor_bin
    environment:
      - ID_SENSOR=3
      - NOME=Geladeira_3
      - TIPO_SENSOR=geladeira
      - TEMP_MIN=3.0
      - TEMP_MAX=5.0
      - HOST_INTEGRADOR=172.16.103.2:9090
    volumes:
      - ./fisica:/app/fisica
    networks:
      - rede_iot
    depends_on: [atuador]

  sensor4:
    build:
      context: .
      dockerfile: ./device/Dockerfile
    command: ./sensor_bin
    environment:
      - ID_SENSOR=4
      - NOME=Freezer_4
      - TIPO_SENSOR=freezer
      - TEMP_MIN=-18.0
      - TEMP_MAX=-15.0
      - HOST_INTEGRADOR=172.16.103.2:9090
    volumes:
      - ./fisica:/app/fisica
    networks:
      - rede_iot
    depends_on: [atuador]

  sensor5:
    build:
      context: .
      dockerfile: ./device/Dockerfile
    command: ./sensor_bin
    environment:
      - ID_SENSOR=5
      - NOME=Freezer_5
      - TIPO_SENSOR=freezer
      - TEMP_MIN=-20.0
      - TEMP_MAX=-10.0
      - HOST_INTEGRADOR=172.16.103.2:9090
    volumes:
      - ./fisica:/app/fisica
    networks:
      - rede_iot
    depends_on: [atuador]

networks:
  rede_iot:
    driver: bridge